services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network

  number-generate-service:
    build:
      context: ../NumberGenerate
      dockerfile: Dockerfile
    container_name: number-generate-service
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - redis
    networks:
      - app-network

  order-service:
    build:
      context: ../order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orders_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      NUMBER_SERVICE_URL: http://number-generate-service:8085
    depends_on:
      - postgres
      - number-generate-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
